services:
  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: redis
    volumes:
      - /mnt/redis-docker:/data
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "pipipi", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    container_name: mongodb
    volumes:
      - /mnt/mongodb-docker:/data/db
    command: mongod --config /etc/mongo/mongod.conf
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mydb
      MONGO_INITDB_ROOT_PASSWORD: pipipi
      MONGO_INITDB_DATABASE: mydb
    healthcheck:
      test: test $$(echo "db.version()" | mongo --port 27017 --quiet)
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx-proxy
    ports:
      - "8080:8080" # Map host 8080 to Nginx container 8080
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  reactnode-file-server:
    build:
      context: .
      dockerfile: reactnode-file-server.Dockerfile
    container_name: reactnode-file-server
    expose:
      - "8083"
      - "8084" # Expose internally for Nginx to access
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /mnt/tmp_dev:/mnt/tmp
      - /mnt/storage:/mnt/storage
      - .:/app/
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  reactnode-server:
    build:
      context: .
      dockerfile: reactnode-server.Dockerfile
    container_name: reactnode-server
    expose:
      - "8082" # Expose internally for Nginx to access
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /mnt/tmp_dev:/mnt/tmp
      - /mnt/storage:/mnt/storage
      - .:/app/
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: unless-stopped

